prefix                     = "maniak"
ec2_key_pair_name          = "maniak-ptfe-dev-key"
eks_cluster_version        = "1.29"
min_consul_version         = "1.18.1"     #Version used when deploying HCP Consul
consul_version             = "1.19.1-ent" # Version used in helm values for dataplane and self-hosted setups
consul_helm_chart_version  = "1.4.1"
consul_helm_chart_template = "values-server-sm-apigw.yaml"
#consul_helm_chart_template = "values-server.yaml"
#consul_helm_chart_template = "values-dataplane.yaml"
consul_partition = "default"